name: Docker Image CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Determine if latest
        id: determine_latest
        env:
          VERSION: ${{ steps.extract_version.outputs.VERSION }}
        run: |
          if [[ "$VERSION" == *"-release"* ]]; then
            echo "LATEST=true" >> $GITHUB_OUTPUT
          else
            echo "LATEST=false" >> $GITHUB_OUTPUT
          fi
      - name: Set tags
        id: set_tags
        env:
          VERSION: ${{ steps.extract_version.outputs.VERSION }}
          LATEST: ${{ steps.determine_latest.outputs.LATEST }}
        run: |
          TAGS="hanjiaming/jade:$VERSION"
          if [ "$LATEST" = "true" ]; then
            TAGS="$TAGS,hanjiaming/jade:latest"
          fi
          echo "TAGS=$TAGS" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAGS }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hanjiaming/jade
          readme-filepath: ./docker-readme.md
